import Link from "next/link";
export const metadata={title:"Services & Scale"};
const levels=[
{number:"01",name:"Tiny Worlds",time:"1–3 weeks",best:"Small scenes, gifts, compact concepts, one strong vignette, intimate shelf-scale work.",complexity:"Focused narrative · restrained footprint · selective detail",note:"Ideal when one moment or one room matters more than breadth."},
{number:"02",name:"Medium Worlds",time:"3–8 weeks",best:"Layered interiors, small buildings, richer street scenes, stronger storytelling, multiple focal points.",complexity:"Deeper detail · more custom elements · stronger environmental narrative",note:"A flexible format for personal and collector commissions."},
{number:"03",name:"Large Worlds",time:"2–6 months",best:"Complex immersive commissions, multiple structures, dense urban or rural environments, larger bespoke displays.",complexity:"Research-heavy · architectural complexity · multiple zones · advanced lighting possible",note:"Designed around viewing experience, transport, display, and long-form build planning."},
{number:"04",name:"Museum / Exhibition Worlds",time:"6–12+ months",best:"Public, educational, institutional, interpretive, brand, or major showcase work.",complexity:"Institutional brief · durability · modularity · interpretation · installation planning",note:"Developed with the institution around audience, access, conservation, safety, and exhibition requirements."}
];
export default function ServicesPage(){return <>
  <section className="page-hero page-shell"><p className="kicker">Services / scale</p><h1>Four levels of ambition. One custom process.</h1><p className="lede">Size matters, but complexity matters more. A tiny interior packed with bespoke objects can demand more studio time than a physically larger but simpler landscape.</p></section>
  <section className="service-list page-shell">{levels.map((item)=><article key={item.number}><div className="service-number">{item.number}</div><div><p className="kicker">{item.name}</p><h2>{item.time}</h2></div><div><p>{item.best}</p><p className="service-complexity">{item.complexity}</p><p>{item.note}</p></div></article>)}</section>
  <section className="pricing-logic"><div className="page-shell pricing-grid"><div><p className="kicker light">Pricing logic</p><h2>Quoted by the world, not by the centimetre.</h2></div><div><p>Exact pricing is quote-based. The proposal considers research depth, overall footprint, architectural complexity, number of figures and handmade props, lighting, materials, specialty finishes, protective display needs, packaging, destination, and installation.</p><p>The purpose of the first inquiry is not to force a client into a preset tier. It is to establish a realistic relationship between ambition, time, and budget.</p><Link className="button brass" href="/contact">Ask for a project quote</Link></div></div></section>
</>;}
