import Link from "next/link";
export const metadata={title:"FAQ"};
const faqs=[
["How do commissions work?","You send a project brief, the studio discusses concept and scope with you, then prepares a proposal covering direction, approximate scale, timeline, staged payments, and quote. Production begins after approval and the first required payment stage."],
["How long does a project take?","Typical working ranges are 1–3 weeks for Tiny Worlds, 3–8 weeks for Medium Worlds, 2–6 months for Large Worlds, and 6–12+ months for Museum / Exhibition Worlds. Complexity, research, approvals, shipping, or installation can change the schedule."],
["Can you recreate a real place?","Yes. A commission can be based on a real building, street, room, landscape, family place, or historic environment. The studio will clarify whether the goal is faithful reconstruction, atmospheric interpretation, or a blend of both."],
["Can I choose a fully static world?","Yes. Every project can be developed as a completely static miniature or enhanced with selected practical effects. Lighting, water, sound, atmosphere, movement and other systems are optional and are included only when they genuinely support the concept and are agreed in the proposal."],
["Can you make historical scenes?","Yes. Historical work is approached through architecture, clothing, material culture, signage, objects, and context. The intention is thoughtful, atmospheric work rather than spectacle."],
["Do you do spooky or gothic commissions?","Yes. Dark, uncanny, gothic, ruined, occult-adjacent, or supernatural atmospheres can all fit the studio. The emphasis is visual storytelling and mood. Gore is not part of the studio direction."],
["Do you make war scenes?","Historically inspired conflict scenes can be considered when the subject is handled thoughtfully. The studio does not use gore as a visual attraction; the emphasis remains context, place, people, material detail, and atmosphere."],
["Do you ship?","Shipping is assessed per project. Fragility, dimensions, protective cases, crating, destination, customs, insurance, and whether installation is required all affect the delivery plan and quote."],
["What is the payment structure?","Custom commissions use staged payments. The exact stages and due points are stated in the proposal so both sides know what is required before production milestones."],
["Can I cancel?","Once production has begun, the studio treats the commission as committed because research, materials, scheduling, and build time are allocated specifically to that piece. Any mandatory consumer rights that cannot legally be excluded still apply."],
["Do you make museum-scale work?","Yes. Museum and exhibition-scale projects use a dedicated scope covering research, durability, public interaction, interpretation, transport, installation, maintenance access and institutional requirements."],
["Will I see the finished piece before it ships?","Yes. Commissioned pieces receive final photography before protective packing begins. Where practical effects are included, they are tested before dispatch. The approved photographs create a clear reference for the piece’s appearance and condition before shipping."],
["What if my piece arrives different from the approved version?","If the delivered piece materially differs from its agreed specification or documented pre-shipping condition, contact the studio with clear photographs showing the issue. Where the problem is a manufacturing or conformity issue attributable to the studio, the appropriate remedy is provided without charge, subject to applicable law."],
["What if an integrated effect stops working?","Send clear photographs or a short video showing the affected feature. The studio will first diagnose the issue remotely where possible. Manufacturing or installation faults within the applicable guarantee or aftercare period are handled without charge; external damage or unauthorised modification may require a paid repair."],
["Is there a two-year guarantee?","For private consumers in the EU, statutory conformity rights include the minimum legal guarantee required by applicable law. Miniature Worlds Studio also provides two-year technical aftercare for manufacturing or installation faults in integrated systems. This policy never reduces any mandatory rights available in the buyer’s country."]
];
export default function FAQPage(){return <section className="faq-page page-shell"><header className="page-hero compact"><p className="kicker">FAQ</p><h1>Before the first sketch.</h1><p className="lede">The practical questions behind commissioning one-off miniature work.</p></header><div className="faq-list">{faqs.map(([question,answer],index)=><details key={question}><summary><span>{String(index+1).padStart(2,"0")}</span><h2>{question}</h2><i aria-hidden="true">+</i></summary><p>{answer}</p></details>)}</div><div className="simple-cta"><div><p className="kicker">Still deciding?</p><h2>A rough idea is enough for a first conversation.</h2></div><Link className="button brass" href="/contact">Start an inquiry</Link></div></section>;}
